name: housekeeping
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - arrow==1.3.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cinemagoer==2023.5.1
      - click==8.1.7
      - diskcache==5.6.3
      - idna==3.10
      - imdbpy==2022.7.9
      - lxml==5.3.0
      - packaging==24.1
      - parse-torrent-title==2.8.1
      - pathvalidate==3.2.0
      - pipdeptree==2.23.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.3
      - six==1.16.0
      - sqlalchemy==2.0.36
      - tmdbsimple==2.9.1
      - trakt-py==4.4.0
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - xmltodict==0.13.0
