name: housekeeper
channels:
  - defaults
dependencies:
  - ca-certificates=2024.3.11
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.8.15
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
