---

log_level: INFO
tmdb_api_key: TMDB_API_KEY
dry_run: false
hd_media_file_size: 300000000 # 300 MB
min_dir_size: 100000000 # 100 MB
min_file_size: 50000000 # 50 MB
trakt:
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
  application_id: APPLICATION_ID

plex:
  watched_url: https://rss.plex.tv/id

radarr:
  api_key: API_KEY
  url: http://192.168.1.2:7878/

sonarr:
  api_key: API_KEY
  url: http://192.168.1.3:8989/

mac:
  watched_movies_media_dir: /path/to/watched
  watched_series_media_dir: /path/to/watched_series
  deleted_media_dir: /path/to/deleted_media
  pre_seeding_dir: /path/to/pre_seeding # Downloaded media on another machine
  seeding_dir: /path/to/seeding
  unsorted_media_dirs:
    - /path/to/unsorted
    - /path/to/seeding
  media_dirs:
    series: /path/to/series
    movies: /path/to/movies/new
    documentaries: /path/to/movies/documentary
    unsorted: /path/to/unsorted
    arabic: /path/to/movies/arabic
    seeding: /path/to/seeding
  jellyfin_nfo_fix:
    text_replacements:
      - replace_text: /path/to/
        replace_with_text: smb://


nas:
  fix_nas_permissions: true
  watched_movies_media_dir: /path/to/watched
  watched_series_media_dir: /path/to/watched_series
  deleted_media_dir: /path/to/deleted_media
  pre_seeding_dir: /path/to/pre_seeding # Downloaded media on another machine
  seeding_dir: /path/to/seeding
  unsorted_media_dirs:
    - /path/to/unsorted
    - /path/to/seeding
  media_dirs:
    series: /path/to/series
    movies: /path/to/movies/new
    documentaries: /path/to/movies/documentary
    unsorted: /path/to/unsorted
    arabic: /path/to/movies/arabic
    seeding: /path/to/seeding
  jellyfin_nfo_fix:
    text_replacements:
      - replace_text: /path/to/
        replace_with_text: smb://


